language: python

python:
- "3.7" 

before_install: 
- sudo apt-get install pandoc

addons:
apt_packages:
- pandoc

install:
- pip install git+https://github.com/AAFC-BICoE/json-schema2adoc.git@dev

script:
- generate_api_doc schema/ schema/
- for f in schema/*.adoc; do filename=$(basename -s .adoc $f); pandoc $f -s -o schema/ schema/$filename.html; done #Pandoc command for generating HTML from Asciidoc

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN 
keep_history: true
on:
branch: json-schema
