language: python

python:
 - "3.7" 

before_install: 
 - sudo apt-get install pandoc

addons:
 apt_packages:
  - pandoc

install:
 - pip install git+https://github.com/AAFC-BICoE/json-schema2adoc.git@dev

script:
 - generate_api_doc schema/ schema/
 - pandoc object-store-rest-api.adoc -s -o index.html

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN 
 keep_history: true
 on:
  branch: json-schema
